apiVersion: v1
kind: Pod
metadata:
  name: exp-sim-/id/
  labels:
    app: exp-sim-/id/
spec:
  containers:
    - name: exp-sim-/id/
      image: semagrow/kobe-evaluator
      imagePullPolicy: Always
      env:
        - name: ENDPOINT
          value: "http://semagrow-/id/.default.svc.cluster.local:8080/SemaGrow/sparql"
        - name: TIMEOUT
          value: "600000"
        - name: EVAL_RUNS
          value: "5"
      volumeMounts:
        - mountPath: /etc/querySet
          name: queryset
  volumes:
    - name: queryset
      hostPath:
        path: /root/invekos/querySetSimple
        type: Directory
  nodeName: node1
  restartPolicy: OnFailure