apiVersion: v1
kind: Service
metadata:
  name: invekos-/id/
spec:
  selector:
    app: invekos-/id/
  ports:
    - name: invekos-/id/-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invekos-/id/
  labels:
    app: invekos-/id/
spec:
  selector:
    matchLabels:
      app: invekos-/id/
  template:
    metadata:
      labels:
        app: invekos-/id/
    spec:
      containers:
        - name: postgis
          image: bde2020/postgis
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/9.4/main/
              name: postgis-dir
        - name: strabon
          image: antru6/strabon
          imagePullPolicy: Always
          env:
            - name: DOWNLOAD_URL
              value: "http://estia.default.svc.cluster.local/dumps/invekos-/id/.tar.gz"
            - name: DATASET_NAME
              value: "invekos-/id/"
            - name: STRABON_CONNECTION_hostname
              value: "localhost"
            - name: STRABON_CONNECTION_port
              value: "5432"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /kobe/dataset/
              name: strabon-dir
      volumes:
        - name: strabon-dir
          hostPath:
            path: /root/strabondir-/id/
            type: Directory
        - name: postgis-dir
          hostPath:
            path: /root/postgisdir-/id/
            type: Directory
      nodeName: node0
