apiVersion: v1
kind: Service
metadata:
  name: semagrow-/id/
spec:
  selector:
    app: semagrow-/id/
  ports:
    - name: semagrow-/id/-ui
      protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semagrow-/id/
  labels:
    app: semagrow-/id/
spec:
  selector:
    matchLabels:
      app: semagrow-/id/
  template:
    metadata:
      labels:
        app: semagrow-/id/
    spec:
      containers:
        - name: semagrow
          image: antru6/semagrow:feat-geospatial-selector
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/default/semagrow/
              name: metadata
      volumes:
        - name: metadata
          hostPath:
            path: /root/semagrow/semagrow-/id/
            type: Directory
      nodeName: node6
